---
# install_and_configure_logwatch/tasks/main.yml

- name: 'Install logwatch package without reboot'
  ansible.builtin.package:
    name: 'logwatch'
    state: 'present'
  when:
    - 'ansible_os_family != "openSUSE MicroOS"'
    - 'ansible_os_family != "openSUSE Leap Micro"'

- name: 'Install logwatch package with reboot on openSUSE MicroOS or openSUSE Leap Micro'
  ansible.builtin.package:
    name: 'logwatch'
    state: 'present'
  when:
    - '
      ansible_os_family == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      '
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Trigger reboot when using transactional updates'
  ansible.builtin.meta: flush_handlers

- name: 'Create /etc/logwatch/conf/logwatch.conf'
  ansible.builtin.template:
    src: 'logwatch.conf.j2'
    dest: '/etc/logwatch/conf/logwatch.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Enable Logwatch timer on openSUSE MicroOS or on SLES15.* / openSUSE 15.* or higher'
  ansible.builtin.systemd:
    name: 'logwatch.timer'
    state: 'started'
    enabled: 'yes'
  when: '
    ansible_os_family == "openSUSE MicroOS" or
    (ansible_os_family == "Suse" and ansible_distribution_major_version >= "15")
    '
