---
# install_and_configure_logwatch/tasks/main.yml

- name: 'Install logwatch package without reboot'
  ansible.builtin.package:
    name: 'logwatch'
    state: 'present'
  when:
    - 'not ansible_os_family == "openSUSE MicroOS"'
    - 'not ansible_os_family == "openSUSE Leap Micro"'
    - 'not ansible_pkg_mgr == "atomic_container"'

- name: 'Install logwatch package with reboot on openSUSE MicroOS or openSUSE Leap Micro'
  ansible.builtin.package:
    name: 'logwatch'
    state: 'present'
  when:
    - '
      ansible_os_family == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      '
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Trigger reboot when using transactional updates'
  ansible.builtin.meta: flush_handlers

- name: 'Create /etc/logwatch/conf/logwatch.conf'
  ansible.builtin.template:
    src: 'logwatch.conf.j2'
    dest: '/etc/logwatch/conf/logwatch.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Run tasks from systemd_timer.yml on openSUSE/SUSE machines'
  ansible.builtin.include_tasks: systemd_timer.yml
  when:
    # openSUSE Leap / Leap Micro are still using cron
    # Debian 11 is still using cron
    # RHEL8/Rocky8/AlmaLinux8 are still using cron
    - '
      ansible_os_family == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE Tumbleweed"
      '
